# Generated by Django 2.1.4 on 2019-01-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
    ]
