# Generated by Django 2.1.4 on 2019-01-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_auto_20190106_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='content',
        ),
    ]
