# Generated by Django 2.1.4 on 2019-01-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='amigos',
            field=models.ManyToManyField(related_name='_perfil_amigos_+', to='perfil.Perfil'),
        ),
    ]
