# Generated by Django 2.1.4 on 2019-01-07 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20190107_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 10, 55, 26, 340403, tzinfo=utc)),
        ),
    ]
