# Generated by Django 2.1.5 on 2019-01-07 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20190107_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.ManyToManyField(related_name='blockers', to='perfil.Profile'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 19, 42, 12, 890806, tzinfo=utc)),
        ),
    ]
