# Generated by Django 2.1.5 on 2019-01-07 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20190107_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 19, 56, 33, 891237, tzinfo=utc)),
        ),
    ]
